CREATE TABLE IF NOT EXISTS MUTUAL_FUND
    (
        SYMBOL CHAR(3) PRIMARY KEY,
        NAME VARCHAR(10) NOT NULL,
        DESCRIPTION VARCHAR(30),
        CATEGORY VARCHAR(10),
        T_NUM_SHARES INTEGER,
        C_DATE DATE
    );

CREATE TABLE IF NOT EXISTS LOCATION
    (
        LOCATION_ID INTEGER PRIMARY KEY,
        STATE VARCHAR(3),
        CITY VARCHAR(10),
        POSTCODE VARCHAR(5)
    );

CREATE TABLE IF NOT EXISTS COMPANY
    (
        COMPANY_ID INTEGER PRIMARY KEY,
        NAME VARCHAR(30) NOT NULL,
        CEO_lname VARCHAR(20),
        CEO_fname VARCHAR(20),
        LOCATION_ID INTEGER REFERENCES LOCATION
    );

CREATE TABLE IF NOT EXISTS USERS
    (
        LOGIN VARCHAR(30) PRIMARY KEY,
        EMAIL VARCHAR(30),
        NAME VARCHAR(30),
        ADDRESS VARCHAR(50),
        PASSWORD VARCHAR(15)
    );

CREATE TABLE IF NOT EXISTS CUSTOMER
    (
        CUSTOMER_ID VARCHAR(30) REFERENCES USERS(LOGIN) PRIMARY KEY,
        BALANCES FLOAT
    );

CREATE TABLE IF NOT EXISTS ADMINISTRATOR
    (
        ADMINISTRATOR_ID VARCHAR(30) REFERENCES USERS(LOGIN) PRIMARY KEY,
    );

CREATE TABLE TRANSACTION_TYPE
    (
        TRANSACTION_TYPE VARCHAR(20) PRIMARY KEY
    )

INSERT INTO TRANSACTION_TYPE VALUES ('INVESTMENT');
INSERT INTO TRANSACTION_TYPE VALUES ('DEPOSIT');

CREATE TABLE TRANSACTIONS
    (
        TRANS_ID INTEGER PRIMARY KEY,
        TRANSACTION_TYPE REFERENCES TRANSACTION_TYPE
    );