CREATE TABLE IF NOT EXISTS MUTUAL_FUND
    (
        SYMBOL CHAR(3) PRIMARY KEY,
        NAME VARCHAR(10) NOT NULL,
        DESCRIPTION VARCHAR(30),
        CATEGORY VARCHAR(10),
        T_NUM_SHARES INTEGER,
        C_DATE DATE
    );

CREATE TABLE IF NOT EXISTS LOCATION
    (
        LOCATION_ID INTEGER PRIMARY KEY,
        STATE VARCHAR(3),
        CITY VARCHAR(10),
        POSTCODE VARCHAR(5)
    );

CREATE TABLE IF NOT EXISTS COMPANY
    (
        COMPANY_ID INTEGER PRIMARY KEY,
        NAME VARCHAR(30) NOT NULL,
        CEO_lname VARCHAR(20),
        CEO_fname VARCHAR(20),
        LOCATION_ID INTEGER REFERENCES LOCATION(LOCATION_ID)
    );