CREATE TABLE IF NOT EXISTS COMPANY
    (
        COMPANY_ID INTEGER PRIMARY KEY NOT NULL,
        "NAME" VARCHAR(30) NOT NULL,
        CEO_lname VARCHAR(20),
        CEO_fname VARCHAR(20)
    );

CREATE TABLE IF NOT EXISTS MUTUAL_FUND 
    (
        SYMBOL CHAR(3) UNIQUE,
        COMPANY_ID INTEGER,
        FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY ON DELETE CASCADE,
        PRIMARY KEY (SYMBOL,COMPANY_ID),
        "NAME" VARCHAR(10) NOT NULL,
        DESCRIPTION VARCHAR(30),
        CATEGORY VARCHAR(10),
        T_NUM_SHARES INTEGER,
        C_DATE DATE NOT NULL
    );

CREATE TABLE IF NOT EXISTS closing_price
   (
	PRICE INTEGER,
	P_DATE DATE NOT NULL,
	SYMBOL CHAR(3) REFERENCES MUTUAL_FUND(SYMBOL),
	PRIMARY KEY (P_DATE,SYMBOL)
   );

CREATE TABLE IF NOT EXISTS "LOCATION"
    (
	STATE VARCHAR(3) DEFAULT 'NSW',  
        CITY VARCHAR(10),
        POSTCODE INTEGER,
        COMPANY_ID INTEGER REFERENCES COMPANY(COMPANY_ID) ON DELETE CASCADE,
        PRIMARY KEY (COMPANY_ID)
    );

CREATE TABLE IF NOT EXISTS USERS
    (
        LOGIN VARCHAR(30) NOT NULL,
        PRIMARY KEY (LOGIN),
        EMAIL VARCHAR(30),
        "NAME" VARCHAR(30),
        ADDRESS VARCHAR(50),
        "PASSWORD" VARCHAR(15)
    );

CREATE TABLE IF NOT EXISTS CUSTOMER
    (
        CUSTOMER_ID VARCHAR(30) NOT NULL REFERENCES USERS(LOGIN),
        PRIMARY KEY (CUSTOMER_ID),
        BALANCES FLOAT
    );

CREATE TABLE IF NOT EXISTS ADMINISTRATOR
    (
        ADMINISTRATOR_ID VARCHAR(30) NOT NULL REFERENCES USERS(LOGIN),
        PRIMARY KEY (ADMINISTRATOR_ID)
    );

CREATE TABLE IF NOT EXISTS R_PREFER
    (
    PERCENTAGE INTEGER, 
    SYMBOL CHAR(3) REFERENCES MUTUAL_FUND(SYMBOL), 
    COMPANY_ID INTEGER REFERENCES COMPANY(COMPANY_ID),   
    CUSTOMER_ID VARCHAR(30) REFERENCES CUSTOMER(CUSTOMER_ID), 
    PRIMARY KEY (SYMBOL, COMPANY_ID, CUSTOMER_ID) 
    );

CREATE TABLE IF NOT EXISTS R_OWNS
    (
    SHARES INTEGER,
    SYMBOL CHAR(3) REFERENCES MUTUAL_FUND(SYMBOL), 
    COMPANY_ID INTEGER REFERENCES COMPANY(COMPANY_ID),  
    CUSTOMER_ID VARCHAR(30) REFERENCES CUSTOMER(CUSTOMER_ID), 
    PRIMARY KEY (SYMBOL, COMPANY_ID, CUSTOMER_ID) 
    );

CREATE TABLE IF NOT EXISTS TRANSACTIONS
    (
        TRANS_ID INTEGER PRIMARY KEY
    );

CREATE TABLE IF NOT EXISTS INVESTMENT_TRANS
    (
        TRANS_ID INTEGER REFERENCES TRANSACTIONS PRIMARY KEY
    );

CREATE TABLE IF NOT EXISTS DEPOSIT_TRANS
    (
        TRANS_ID INTEGER REFERENCES TRANSACTIONS PRIMARY KEY
    );

CREATE TABLE IF NOT EXISTS R_DEPOSIT_TRANS1
    (
        TRANS_ID INTEGER REFERENCES DEPOSIT_TRANS(TRANS_ID),
        CUSTOMER_ID VARCHAR(30) REFERENCES CUSTOMER(CUSTOMER_ID),
        PRIMARY KEY (TRANS_ID, CUSTOMER_ID),
        t_date DATE NOT NULL,
        AMOUNT INTEGER
    );

CREATE TABLE IF NOT EXISTS R_PROFOLIO_ACTION
    (
        t_date DATE NOT NULL,
        PRICE INTEGER,
        NUM_SHARES INTEGER,
        AMOUNT INTEGER,
        "ACTION" VARCHAR (10),
        SYMBOL CHAR(3) REFERENCES MUTUAL_FUND(SYMBOL), 
        COMPANY_ID INTEGER REFERENCES COMPANY(COMPANY_ID), 
        CUSTOMER_ID VARCHAR(30) REFERENCES CUSTOMER(CUSTOMER_ID), 
        TRANS_ID INTEGER REFERENCES INVESTMENT_TRANS(TRANS_ID),
        PRIMARY KEY (SYMBOL, COMPANY_ID, CUSTOMER_ID, TRANS_ID),
        CHECK (AMOUNT = (NUM_SHARES*PRICE)),  
        CHECK ("ACTION" in ('sell','buy')) 
    );

INSERT INTO COMPANY (COMPANY_ID,"NAME",CEO_lname,CEO_fname)
    VALUES (007,'Apple','Cook','Tim');
INSERT INTO MUTUAL_FUND (SYMBOL,COMPANY_ID,"NAME",DESCRIPTION,CATEGORY,T_NUM_SHARES,C_DATE)
    VALUES ('AP',007,'INVESTMENT','makemoney','invest',1000,'2019-05-01');
INSERT INTO closing_price (PRICE,P_DATE,SYMBOL)
    VALUES (100, '2019-05-01','AP');
INSERT INTO "LOCATION" (STATE,CITY,POSTCODE,COMPANY_ID)
    VALUES ('NSW','SYDNEY',2008,007);
INSERT INTO USERS (LOGIN,EMAIL,"NAME",ADDRESS,"PASSWORD")
    VALUES ('adminid','admin@apple.com','TimCook','address','password');
INSERT INTO USERS (LOGIN,EMAIL,"NAME",ADDRESS,"PASSWORD")
    VALUES ('customerid','customer@apple.com','BillGates','address','password');
INSERT INTO CUSTOMER (CUSTOMER_ID,BALANCES)
    VALUES ('customerid',1000);
INSERT INTO ADMINISTRATOR (ADMINISTRATOR_ID)
    VALUES ('adminid');
INSERT INTO R_PREFER (PERCENTAGE,SYMBOL,COMPANY_ID,CUSTOMER_ID)
    VALUES (80,'AP',007,'customerid');
INSERT INTO R_OWNS (SHARES,SYMBOL,COMPANY_ID,CUSTOMER_ID)
    VALUES (50,'AP',007,'customerid');
INSERT INTO TRANSACTIONS (TRANS_ID)
    VALUES (3);
INSERT INTO TRANSACTIONS (TRANS_ID)
    VALUES (4);
INSERT INTO INVESTMENT_TRANS (TRANS_ID)
    VALUES (4);
INSERT INTO DEPOSIT_TRANS (TRANS_ID)
    VALUES (3);
INSERT INTO R_DEPOSIT_TRANS1 (TRANS_ID,CUSTOMER_ID,t_date,AMOUNT)
    VALUES (3,'customerid','2019-04-01',300);
INSERT INTO R_PROFOLIO_ACTION (t_date,PRICE,NUM_SHARES,AMOUNT,"ACTION",SYMBOL,COMPANY_ID,CUSTOMER_ID,TRANS_ID)
    VALUES ('2019-05-01',100,5,500,'buy','AP',007,'customerid',4);
