CREATE TABLE IF NOT EXISTS COMPANY
    (
        COMPANY_ID INTEGER PRIMARY KEY NOT NULL,
        COMPANY_NAME VARCHAR(30) NOT NULL,
        CEO_lname VARCHAR(20),
        CEO_fname VARCHAR(20)
    );

CREATE TABLE IF NOT EXISTS MUTUAL_FUND 
    (
        SYMBOL CHAR(3),
        FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY ON DELETE CASCADE,
        PRIMARY KEY (SYMBOL,COMPANY_ID),
        M_NAME VARCHAR(10) NOT NULL,
        DESCRIPTION VARCHAR(30),
        CATEGORY VARCHAR(10),
        T_NUM_SHARES INTEGER,
        C_DATE DATE NOT NULL
    );

CREATE TABLE IF NOT EXISTS closing_price
(
    PRICE INTEGER,
    P_DATE DATE NOT NULL,
    FOREIGN KEY (SYMBOL) REFERENCES MUTUAL_FUND,
    PRIMARY KEY (P_DATE,SYMBOL)
);

CREATE TABLE IF NOT EXISTS "LOCATION"
    (
	STATE VARCHAR(3) DEFAULT 'NSW',  
        CITY VARCHAR(10),
        POSTCODE INTEGER,
        FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY ON DELETE CASCADE,
        PRIMARY KEY (COMPANY_ID)
    );

CREATE TABLE IF NOT EXISTS USERS
    (
        LOGIN VARCHAR(30) PRIMARY KEY,
        EMAIL VARCHAR(30),
        USER_NAME VARCHAR(30),
        ADDRESS VARCHAR(50),
        PASSWORD VARCHAR(15)
    );

CREATE TABLE IF NOT EXISTS CUSTOMER
    (
        CUSTOMER_ID VARCHAR(30) REFERENCES USERS(LOGIN) PRIMARY KEY,
        BALANCES FLOAT
    );

CREATE TABLE IF NOT EXISTS ADMINISTRATOR
    (
        ADMINISTRATOR_ID VARCHAR(30) REFERENCES USERS(LOGIN) PRIMARY KEY
    );

CREATE TABLE IF NOT EXISTS R_PREFER
    (
	PERCENTAGE INTEGER, 
	FOREIGN KEY (SYMBOL) REFERENCES MUTUAL_FUND, 
	FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY,   
        FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER, 
        PRIMARY KEY (SYMBOL, COMPANY_ID, CUSTOMER_ID) 
    );

CREATE TABLE IF NOT EXISTS R_OWNS
    (
	SHARES INTEGER,
	FOREIGN KEY (SYMBOL) REFERENCES MUTUAL_FUND, 
	FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY,  
        FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER, 
        PRIMARY KEY (SYMBOL, COMPANY_ID, CUSTOMER_ID) 
    );

CREATE TABLE IF NOT EXISTS TRANSACTIONS
    (
        TRANS_ID INTEGER PRIMARY KEY
    );

CREATE TABLE IF NOT EXISTS INVESTMENT_TRANS
    (
        TRANS_ID INTEGER REFERENCES TRANSACTIONS PRIMARY KEY
    );

CREATE TABLE IF NOT EXISTS DEPOSIT_TRANS
    (
        TRANS_ID INTEGER REFERENCES TRANSACTIONS PRIMARY KEY
    );

CREATE TABLE IF NOT EXISTS R_DEPOSIT_TRANS
    (
        FOREIGN KEY (TRANS_ID) REFERENCES DEPOSIT_TRANS,
        FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER,
        PRIMARY KEY (TRANS_ID, CUSTOMER_ID),
        t_date DATE NOT NULL,
        AMOUNT INTEGER
    );

CREATE TABLE IF NOT EXISTS R_PROFOLIO_ACTION
    (
        t_date DATE NOT NULL,
        PRICE INTEGER,
        NUM_SHARES INTEGER,
        AMOUNT INTEGER,
        ACTIONS VARCHAR (10),
        FOREIGN KEY (SYMBOL) REFERENCES MUTUAL_FUND, 
        FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY, 
        FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER, 
        FOREIGN KEY (TRANS_ID) REFERENCES INVESTMENT_TRANS,
        PRIMARY KEY (SYMBOL, COMPANY_ID, CUSTOMER_ID, TRANS_ID),
        CHECK (AMOUNT = (NUM_SHARE*PRICE)),  
        CHECK (ACTIONS = 'sell' or ACTIONS = 'buy') 
    );


INSERT INTO COMPANY VALUES (123,'Apple','Cook','Tim')
INSERT INTO MUTUAL_FUND VALUES ('APP',123,'INVESTMENT','makemoney','invest',1000,'2019-05-01')
INSERT INTO closing_price VALUES (100, '2019-05-01','APP')
INSERT INTO "LOCATION" VALUES ('NSW','SYDNEY',2008,123)
INSERT INTO USERS VALUES ('admin','admin@apple.com','TimCook','address','password')
INSERT INTO USERS VALUES ('customer','customer@apple.co','BillGates','address','password')
INSERT INTO CUSTOMER VALUES ('customer',1000)
INSERT INTO ADMINSTRATOR VALUES ('admin')
INSERT INTO R_PREFER VALUES (80,'APP',123,'customer')
INSERT INTO R_OWNS VALUES (50,'APP',123,'customer')
INSERT INTO TRANSACTIONS VALUES (1)
INSERT INTO TRANSACTIONS VALUES (2)
INSERT INTO INVESTMENT_TRANS VALUES (1)
INSERT INTO DEPOSIT_TRANS VALUES (2)
INSERT INTO R_DEPOSIT_TRANS VALUES (2,'customer','2019-04-31',100)
INSERT INTO R_PROFOLIO_ACTION VALUES ('2019-05-01',100,5,500,'buy','APP',123,'customer',1)


